# Generated by Django 4.0.3 on 2022-04-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.IntegerField(unique=True)),
                ('date_of_arrival', models.DateTimeField(auto_now_add=True)),
                ('location_X', models.IntegerField()),
                ('location_Y', models.IntegerField()),
                ('done_processing', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
