# Generated by Django 4.0.3 on 2022-04-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loactionmanger',
            name='postal_address',
            field=models.IntegerField(unique=True),
        ),
    ]
